# pull official base image
FROM node:6.11-stretch

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY . ./

RUN yarn install

# start app
CMD ["npm", "run", "serve"]
